version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/
    networks:
      - shared_net

  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared_net

  redis:
    image: redis:7
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - shared_net

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - shared_net

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    networks:
      - shared_net

  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - minio_data:/data
    env_file:
      - .env
    command: server /data --console-address ":9001"
    networks:
      - shared_net

  # minio-console:
  #   image: quay.io/minio/console:v0.30.0
  #   container_name: minio-console
  #   depends_on:
  #     - minio
  #   environment:
  #     CONSOLE_MINIO_SERVER: http://minio:9000
  #   command: server
  #   networks:
  #     - shared_net

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  shared_net:
    name: shared_net
    driver: bridge